# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import recommend_pb2 as proto_dot_recommend__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/recommend_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendStub(object):
    """ip: 43.138.152.89:9090
    The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMusic = channel.unary_unary(
                '/proto.Recommend/GetMusic',
                request_serializer=proto_dot_recommend__pb2.RecommendRequest.SerializeToString,
                response_deserializer=proto_dot_recommend__pb2.RecommendReply.FromString,
                _registered_method=True)
        self.UploadMusic = channel.stream_unary(
                '/proto.Recommend/UploadMusic',
                request_serializer=proto_dot_recommend__pb2.UploadMusicRequest.SerializeToString,
                response_deserializer=proto_dot_recommend__pb2.UploadMusicReply.FromString,
                _registered_method=True)


class RecommendServicer(object):
    """ip: 43.138.152.89:9090
    The service definition.
    """

    def GetMusic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadMusic(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMusic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMusic,
                    request_deserializer=proto_dot_recommend__pb2.RecommendRequest.FromString,
                    response_serializer=proto_dot_recommend__pb2.RecommendReply.SerializeToString,
            ),
            'UploadMusic': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadMusic,
                    request_deserializer=proto_dot_recommend__pb2.UploadMusicRequest.FromString,
                    response_serializer=proto_dot_recommend__pb2.UploadMusicReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Recommend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.Recommend', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Recommend(object):
    """ip: 43.138.152.89:9090
    The service definition.
    """

    @staticmethod
    def GetMusic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.Recommend/GetMusic',
            proto_dot_recommend__pb2.RecommendRequest.SerializeToString,
            proto_dot_recommend__pb2.RecommendReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadMusic(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/proto.Recommend/UploadMusic',
            proto_dot_recommend__pb2.UploadMusicRequest.SerializeToString,
            proto_dot_recommend__pb2.UploadMusicReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
