# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/recommend.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/recommend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/recommend.proto\x12\x05proto\"\"\n\x10RecommendRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"!\n\x0eRecommendReply\x12\x0f\n\x07musicId\x18\x01 \x03(\t\"4\n\x12UploadMusicRequest\x12\x0f\n\x07musicId\x18\x01 \x01(\t\x12\r\n\x05\x63hunk\x18\x02 \x01(\x0c\"4\n\x10UploadMusicReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8e\x01\n\tRecommend\x12<\n\x08GetMusic\x12\x17.proto.RecommendRequest\x1a\x15.proto.RecommendReply\"\x00\x12\x43\n\x0bUploadMusic\x12\x19.proto.UploadMusicRequest\x1a\x17.proto.UploadMusicReply(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.recommend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDREQUEST']._serialized_start=32
  _globals['_RECOMMENDREQUEST']._serialized_end=66
  _globals['_RECOMMENDREPLY']._serialized_start=68
  _globals['_RECOMMENDREPLY']._serialized_end=101
  _globals['_UPLOADMUSICREQUEST']._serialized_start=103
  _globals['_UPLOADMUSICREQUEST']._serialized_end=155
  _globals['_UPLOADMUSICREPLY']._serialized_start=157
  _globals['_UPLOADMUSICREPLY']._serialized_end=209
  _globals['_RECOMMEND']._serialized_start=212
  _globals['_RECOMMEND']._serialized_end=354
# @@protoc_insertion_point(module_scope)
